apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rating-deployment
spec:
  selector:
    matchLabels:
      app: movie-rating-service
  template:
    metadata:
      labels:
        app: movie-rating-service
    spec:
      containers:
      - name: movie-rating-service
        image: harbor-repo.vmware.com/movie-rating-service
        ports:
        - containerPort: 8083
